(library
 (name ppx_deriving_melange_runtime_cases)
 (modes :standard melange)
 (modules
  test_case
  test_eq_cases
  test_iter_cases
  test_map_cases
  test_ord_cases
  test_show_cases)
 (preprocess
  (pps ppx_deriving_melange)))

(test
 (name test_eq)
 (modules test_eq)
 (libraries ounit2 ppx_deriving_melange_runtime_cases))

(test
 (name test_iter)
 (modules test_iter)
 (libraries ounit2 ppx_deriving_melange_runtime_cases))

(test
 (name test_map)
 (modules test_map)
 (libraries ounit2 ppx_deriving_melange_runtime_cases))

(test
 (name test_ord)
 (modules test_ord)
 (libraries ounit2 ppx_deriving_melange_runtime_cases))

(test
 (name test_show)
 (modules test_show)
 (libraries ounit2 ppx_deriving_melange_runtime_cases))

(executable
 (name ppx_deriving_melange_standalone)
 (modules ppx_deriving_melange_standalone)
 (libraries ppx_deriving_melange ppxlib))

(cram
 (deps ppx_deriving_melange_standalone.exe))

(melange.emit
 (target node)
 (alias ppx_deriving_melange_runtime_test)
 (modules test_runtime)
 (libraries melange-fest ppx_deriving_melange_runtime_cases)
 (preprocess
  (pps melange.ppx))
 (module_systems
  (es6 mjs)))

(rule
 (alias runtest)
 (deps
  (alias_rec ppx_deriving_melange_runtime_test)
  (:input ./node/test/test_runtime.mjs))
 (action
  (run node %{input})))
